### ISSUE TITLE
Reverting to prior version should clear out the "up to date" flag

### ISSUE THREAD

**Issue by carter2422** [CGCookie/blender-addon-updater#1]
If you revert to an older version, such as from 1.1.3 to 1.1.1 then the update status still reads as `Add-on is up to date`, which is now incorrect.

Upon reversion we need to be sure to clear out the updated status so that it properly shows that an update is available.

**Comment by johnroper100** [comment]
I agree with this.

**Comment by TheDuckCow** [comment]
Further testing to be done, but with v1.1.14 can't seem to replicate. Some additional changes were made to more frequently save the state to disk which likely was the source of the issue.

**Comment by carter2422** [comment]
Sounds good; closing.
