### ISSUE TITLE
Version restriction

### ISSUE THREAD

**Issue by TheDuckCow** [CGCookie/blender-addon-updater#10]
Previously there was a request to create or allow the developer to add a function which restricts the versions to be installed by the updater. This could, as one example, prevent the user from downgrading too far. Ultimately, we could also put checks in for blender versions but would be up to the developer how restrictive this is.

This feature is currently already implemented in the code via a function that the developer passes into the register function, assigning it to an updater class object which is used as a callable whenever checking the versions from the server.

**Comment by TheDuckCow** [comment]
While already implemented, an interesting point is that if you also were to restrict e.g. maximum versions to update to, when if someone was on v4.x and downgraded to v3.x, but the code in 3.x prevented versioning back up to v4.x? My thought is we could, in addition to this function check, also keep an offline record of the addon versions installed at any time to compare against. Maybe is overly complicated, but could be used to work around that particular issue.

**Comment by carter2422** [comment]
Would it be simpler to add both a (optional) minimum and max version? Such that if you have 4.x installed it won't permit downgrading below 4.x, as an example.

**Comment by TheDuckCow** [comment]
I suppose that's valid, if we want to go with this no problem - I'm probably overcomplicating it

**Comment by carter2422** [comment]
Let's keep it simple 👍

**Comment by johnroper100** [comment]
I agree with @carter2422 on this one

**Comment by TheDuckCow** [comment]
Implemented now through the line items:

```
updater.version_min_update = (0,3,1) # min allowed to install, >=
updater.version_max_update = (2,4,5) # max allowed to install, <
updater.skip_tag = skip_tag_function # min and max used in this function
```

where, if the users _does_ want more advanced tag filtering, they can modify the skip_tag_function defined earlier in the file, or they can ignore it.
