### ISSUE TITLE
Account for fatal error in updated add-on

### ISSUE THREAD

**Issue by carter2422** [CGCookie/blender-addon-updater#12]
Do we have any way to account for the scenario in which a developer releases a buggy update, which gets installed, and then fatals out? 

Per Greg Zaal:

> Greg Zaal [4:50 PM]  
> @jonathan @johnroper100 if there is some fatal error in my add-on that prevents it from registering, will the auto update still work? e.g. i accidentally release a broken update, which gets downloaded for all users - once i release a fixed version will the users have to manually update then?

Thoughts @TheDuckCow?

**Comment by TheDuckCow** [comment]
That's an interesting one. In a manual sense, yes. The uodater backs up the previously installed version's code, but you can't restore the backup through blender unless the addon was working enough such that the preferences section was working, or they could manually copy the code from the backup folder into the addons root folder itself. 

Unless we released a supplemental "recovery addon" or some other wider addon management addon that was installed separately, I don't see s real way to get around the issue.

**Comment by carter2422** [comment]
@TheDuckCow couldn't we simply separate the registration functions, with preferences being registered first, such that if the core add-on fails the preferences still load and enable restoring? 

If that works then we can just include that in our integration docs.

**Comment by TheDuckCow** [comment]
Sure that could work, will up to them if they have other code in the preferences panel that works or not but seems reasonable to instruct what you said.  In the same manner, I would have instructions on how to use the "fake install" feature I added for developers (to test installing conditions without necessarily having releases in place)

**Comment by TheDuckCow** [comment]
Added some language around this, closing issue.
