### ISSUE TITLE
Account for different GitHub structures

### ISSUE THREAD

**Issue by TheDuckCow** [CGCookie/blender-addon-updater#17]
Right now, the updater assumes a flat structure of an addon - that is, the root of the github repository is also the addon's root. I have added this to the tutorial to point this out:

> on should have the __init__.py file and relative code structure at the root of the repository, not in a sub folder. The updater will try to install updates by directly installing the repository’s zip file.

The enhancement would be to more intelligently search for the relative addon's root within the zip file, perhaps just searchign by default one level deep or providing an option to the developer to specify which subfolder of the repository to treat as the addon itself. 

Though this is more like an enhancement, I'm treating it like an issue as it could bar some developers from making use of the repository natively.

**Comment by TheDuckCow** [comment]
Notes to self that this code would be relatively easily implemented [around here](https://github.com/CGCookie/blender-addon-updater/blob/76b0a9f31fce1a6404d7497ea365324219a99163/addon_updater.py#L592). As a side note to self.... I thought this was already working as intended, but got a report from someone that perhaps it is not

Reference [project/commit](https://github.com/rymdnisse/http-image.jpeg/tree/52c498ec3971665a76ce0e68682a58c88d7cd99a/http-image-jpeg) thanks to @rymdnisse noting that the referenced commit here was not working, but when moving it [to this structure](https://github.com/rymdnisse/http-image.jpeg/tree/5d4ff32da6a541e5f0438fdc58ac0524857d41b6) it was working.

**Comment by TheDuckCow** [comment]
Note that this enhancement has been completed, thanks to the initial work done by @blanchg we have a convenient structure that allows to integrate with any number of engines and initially did the support for bitbucket itself. 

I have since taken that structure and expanded it to support also GitLab (another hosting site with a git api). It's use is defined _within_ the updater module by:
```
self._engine = GitlabEngine()
```

Or, if you are outside the python module (where you don't have direct access to the engine classes), you can set the engine by:
```
from .addon_updater import Updater as updater
updater.engine = "Github"
# updater.engine = "GitLab"
# updater.engine = "Bitbucket"
```

Issue will be closed once the code is merged in from the according forks on those other platforms for testing.

**Comment by ndee85** [comment]
I would love to have this feature. Because, my github repo has a few more nested directories, as I do not only provide the blender addon in it. Is it possible to define a subfolder? That would be awesome!

If its not yet implemented, can you lead me to the code where something like this would be implemented? I would really love to implement the Addon Updater.

**Comment by ndee85** [comment]
I made some modifications to the addon to create a custom subfolder path for the addon.
Are you interested in a PR to review?

**Comment by TheDuckCow** [comment]
Yes that’d be great Thanks again for finally putting this in, looking forward to reviewing the PR.

**Comment by TheDuckCow** [comment]
Now addressed thanks to @ndee85's [PR here](https://github.com/CGCookie/blender-addon-updater/pull/36)
