### ISSUE TITLE
Support for custom branch(s)

### ISSUE THREAD

**Issue by johnroper100** [CGCookie/blender-addon-updater#20]
Having the ability to give the option to update from the `master` branch is awesome, but in some situations `master` may not be the actual development branch. It would be nice to be able to specify (in addition to `master`) other branches to add to the list of versions to update from.

**Comment by TheDuckCow** [comment]
I've mostly implemented this feature, actually I just need to test it (more). See how it looks in the UI (not also as per [issue 23](https://github.com/CGCookie/blender-addon-updater/issues/23#issuecomment-297027445) I've slightly adjusted how update to {branch} works, won't trigger UI popups as it wasn't doing real timestamp comparisons)

![screen shot 2017-04-25 at 11 14 04 pm](https://cloud.githubusercontent.com/assets/2958461/25416697/223acdce-2a0d-11e7-85c2-f9790362c08a.png)

Code options in the _ops.py, note this is only in the dev branch of this repo right now (meta, right?), but once final testing confirmed it will move into master.
```
# allow 'master' as an option to update to, regardless of release or version
# default behavior: releases will still be used for auto check (popup),
# but the user has the option from user preferences to directly 
# update to the master branch.
updater.include_master = True

# if using "include_master", 
# updater.include_master_branch defaults to 'master' branch if set to none
# updater.include_master_branch = 'dev' # example targeting another branch
updater.include_master_branch = 'dev'
```

**Comment by TheDuckCow** [comment]
One thing that I could look to actually support in the farther future is being able to indicate multiple branches by inputting a list of branches to be available from the dropdown, or even provide an option to show all branches in an enum. But for now, focusing firs ton ensuring this option works well inputting an arbitrary branch (which defaults to master)

**Comment by johnroper100** [comment]
That is fine, it would be nice to have a list like ```branches = ["master", "develop", "testingv3"]``` etc.

**Comment by TheDuckCow** [comment]
Yes I had a similar thought but will require a little more structure, though not terrible.

**Comment by TheDuckCow** [comment]
@johnroper100 implemented as suggested, see the latest code. The first item on the list is used for any "default branch" usage, such as turning the check for update into an update to master button when there are no releases present (other branches specified still accessible from dropdown)

[https://github.com/CGCookie/blender-addon-updater/releases/tag/v1.0.3](https://github.com/CGCookie/blender-addon-updater/releases/tag/v1.0.3)

If including `updater.include_branch_list = ['master', 'dev']`, the result is:
![screen shot 2017-05-05 at 4 51 49 am](https://cloud.githubusercontent.com/assets/2958461/25739137/94612798-314e-11e7-8354-fd1f8b81acae.png)
