### ISSUE TITLE
Update for Gaffer gives URL error

### ISSUE THREAD

**Issue by JoelGodin** [CGCookie/blender-addon-updater#21]
Hitting "Check for update" on Gaffer giver the error "URL error, check internet connection"
![gaff](https://cloud.githubusercontent.com/assets/9205295/24924271/37c97a2e-1ec2-11e7-8b93-301397ca0a01.png)

Gaffer 3.03
4-06-2017 BlenderBot build
Mac OSX 10.12.4

**Comment by TheDuckCow** [comment]
Thanks for looking to log this - Can you confirm whether the same error happens if you intentionally disconnect your internet connection? See that message below the button in your screenshot which says "unknown url type: https". If the message is the same, then perhaps it is a security setting on your computer blocking access from blender reaching out to the web.

**Comment by JoelGodin** [comment]
I just checked with the stable 2.78 and it works fine.  But the latest from Buildbot is not working.

**Comment by TheDuckCow** [comment]
I just tried on the most recent build without issue, so I'm not sure what you ran into. Can you open blender with a terminal console open (let me know if assistance is needed on how to do that - if on windows, easy as going to help > show console).

**Comment by JoelGodin** [comment]
Ok, I have OSX.  Opened Terminal and opened Blender. (latest buildbot as of Apr 23).
Usual terminal stuff after open, then upon hitting 'update gaffer' button get this:

fake_module: addon missing 'bl_info' gives bad performance!: '/Users/joelgodin/Library/Application Support/Blender/2.78/scripts/addons/add_mesh_vertex.py'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Applications/Blender/blender-2.78.0-git20170423.20c9c1b44e-x86_64/blender.app/Contents/Resources/2.78/python/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/Applications/Blender/blender-2.78.0-git20170423.20c9c1b44e-x86_64/blender.app/Contents/Resources/2.78/python/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/joelgodin/Library/Application Support/Blender/2.78/scripts/addons/Gaffer/addon_updater.py", line 1033, in async_check_update
    self.check_for_update(now=now)
  File "/Users/joelgodin/Library/Application Support/Blender/2.78/scripts/addons/Gaffer/addon_updater.py", line 783, in check_for_update
    self.get_tags() # sets self._tags and self._tag_latest
  File "/Users/joelgodin/Library/Application Support/Blender/2.78/scripts/addons/Gaffer/addon_updater.py", line 412, in get_tags
    self._prefiltered_tag_count = len(all_tags)
TypeError: object of type 'NoneType' has no len()

**Comment by gregzaal** [comment]
@TheDuckCow Github page is [here](https://github.com/gregzaal/Gaffer/tags) btw, definitely has tags.

**Comment by JoelGodin** [comment]
Just a reminder, that it works with stable 2.78c but not the latest builds from buildbot.
Something is different in those builds.

**Comment by TheDuckCow** [comment]
Really sorry for the delay here, but I just tried now again with the latest 2.78 as well as 2.80 build bots (Sun July 9th, 2017) as well as master using gaffer v3.0.3 and the issue doesn't seem to be present in either. I tried on OSX, but let me know if the issue happens in any other situations. Let me know if you're still seeing the issue.

Also in the screenshot shared above, below the main button I was seeing it said "unknown url type: https", not sure what could bring that issue up but that is the actual python error that occurred in that case. A [quick search gets me this](https://stackoverflow.com/questions/28376506/urllib-https-request-urlopen-error-unknown-url-type-https); I have seen in various rare cases different people with seemingly limited versions of python being used, including even examples where the urllib library itself isn't present. Perhaps it was a configuration error for that specific python build in that daily build, but it is hard to say.

**Comment by JoelGodin** [comment]
Could have been, because numpy was also missing because of bad builds. Will
try later.
Thanks

**Comment by TheDuckCow** [comment]
Either @JoelGodin or @gregzaal feel free to comment back if in disagreement, but I'm going to close this issue - the root issue was a blender build with a missing library (which shouldn't happen, but even if it does there's now more graceful and silent failing on the updater addon's part).
