### ISSUE TITLE
version_max_update default

### ISSUE THREAD

**Issue by bsavery** [CGCookie/blender-addon-updater#22]
Currently it's 9.9.9... I'd claim it should be higher, i.e if my version is 10.0.0 it won't pass the test.

or do something like set max to -1 or none for no max.

**Comment by bsavery** [comment]
Of course we set our own max but the default should do that I'd claim.

**Comment by TheDuckCow** [comment]
@bsavery  sorry for the delay. What you describe is actually how it already works, you can set it equal to None and it will not consider a max install. Agreed we should change the default to be None, perhaps even for both max and min and leave it to the developer to utilize it. I will make this change in the next update to this repo.

**Comment by TheDuckCow** [comment]
Implemented the change into dev branch, simply toggled which line was commented out as both were there for reference. I kept the min_update value as (0,0,0) as this would seem to be a harmless thing in my point of view as there are no negative versions possible. Thanks again for bringing this point up.
