### ISSUE TITLE
Removing Old Modules

### ISSUE THREAD

**Issue by AndrewPeelMV** [CGCookie/blender-addon-updater#26]
The Add-on updater doesn't appear to remove old modules that have been deleted. From what I can see the zip file is just unpacked into the add-on directory. Are there any plans to clean up any files that have been removed?

**Comment by TheDuckCow** [comment]
That's a good question. Sometimes addons create config files or other items that you don't necessarily want to delete, hence the reason for only overwriting new files found (which is the same way blender behaves when you install an addon over an existing version). It would be doable however to have a force refresh option which would be the equivalent of completely deleting the addon folder and bringing in the new version.

**Comment by AndrewPeelMV** [comment]
Yeah that totally makes sense. I suppose that add-on's would have to store any config files it creates outside of the add-on folder, or the updater would have to keep track of files from the previous version and determine what files should be cleaned up. For what I need it is easy enough to include some custom functionality to the updater to clean up some specific files. Thanks for the info.

**Comment by TheDuckCow** [comment]
Sure thing, thanks for raising the issue and feel free to let us know of any other thoughts or feedback you have - or issues in getting it all set up.
