### ISSUE TITLE
Add-ons update status fails to update after installing older versions

### ISSUE THREAD

**Issue by carter2422** [CGCookie/blender-addon-updater#3]
Continuing discussion from https://github.com/CGCookie/retopoflow/issues/216#issuecomment-235464108

**Comment by TheDuckCow** [comment]
> It persists after a restart (and even a re-install). Auto check was originally disabled but then I tested it with a 1 minute schedule and it still claimed to be up to date.

Interesting. And this was using the release download of v11 or v12? Windows/mac/linux? (in case it's somehow because it can't modify the json file or something strange like that)

**Comment by carter2422** [comment]
Yep, this was with the 1.1.11 release you gave me, installed on Mac.

**Comment by TheDuckCow** [comment]
Further testing to be done, but with v1.1.14 can't seem to replicate. As a side note, when testing consider opening blender via terminal so that if we run into an oddity like that I might be able to better track what occurred.

**Comment by carter2422** [comment]
I'm going to consider this closed. We can reopen if able to replicate again.
