### ISSUE TITLE
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:720)

### ISSUE THREAD

**Issue by ndee85** [CGCookie/blender-addon-updater#35]
Hi,
I am trying to implement the addon updater into my addon. I have setup all basic steps. I left the repo and user name at defaults by now. Just to see if it gets a connection.

At work we use a proxy to connect to the internet. Could it be related to that?

Unfortunately I get the error message above. And within the blender console I get these errors:

`Getting tags from server
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\threading.py
", line 914, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\threading.py
", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\g041481\AppData\Roaming\Blender Foundation\Blender\2.79\scripts
\addons\coa_tools\addon_updater.py", line 1309, in async_check_update
    self.check_for_update(now=now)
  File "C:\Users\g041481\AppData\Roaming\Blender Foundation\Blender\2.79\scripts
\addons\coa_tools\addon_updater.py", line 1035, in check_for_update
    self.get_tags()  # sets self._tags and self._tag_latest
  File "C:\Users\g041481\AppData\Roaming\Blender Foundation\Blender\2.79\scripts
\addons\coa_tools\addon_updater.py", line 523, in get_tags
    self._prefiltered_tag_count = len(all_tags)
TypeError: object of type 'NoneType' has no len()`

Later I will check this from home and see if it works. I will report back. Still would be great if this works with a proxy so my colleagues could update the addon without hassle in the future.

**Comment by ndee85** [comment]
Forgot to mention that the "URL error, check internet connection" exception is thrown.

**Comment by ndee85** [comment]
Ok.. I think I found a solution. It did have nothing to do with proxy settings. Its a problem with the ssl context. I found a solution on this site:
https://forum.manjaro.org/t/how-to-disable-ssl-verification-for-git-etc-through-proxy/20215

Basicall I just needed to `import ssl`
and then add the proper context to the openurl functions like that:

```
context = ssl._create_unverified_context()
urllib.request.urlopen(request,context=context)
```
Would be cool if this can be added by default.

**Comment by TheDuckCow** [comment]
Thanks again for looking into this and finding a solution - looking forward to the PR as discussed.

**Comment by ndee85** [comment]
Hi,
here is the pull request. You may want to take a look and see if its ok.
#36

**Comment by TheDuckCow** [comment]
Thanks again for the contribution, now merged (and now even used by one of my other addons)!

**Comment by Alzy** [comment]
Instead of disabling ssl certificate verification and possibly causing security threats, use the certifi module as @john-shine proposed [here](https://github.com/aio-libs/aiohttp/issues/955#issuecomment-568425975). This example uses aiohttp but should lead you in the right direction even if you're using a different module.
