### ISSUE TITLE
Support for Bitbucket

### ISSUE THREAD

**Issue by TheDuckCow** [CGCookie/blender-addon-updater#4]
Goal: to support Bitbucket hosted code with minimal to no configuration change outside the python module. 

Steps to take
- Initial API exploration nd tests
- Functional version and code grabbing for public repos
- Functional with private repos using necessary keys etc

**Comment by TheDuckCow** [comment]
Notes to self exploring this area. See [threads such as this](https://bitbucket.org/site/master/issues/6548/download-tar-zip-with-oauth-api-token). It appears there is a straightforward structure of using https://bitbucket.org/{user}/{repo}/get/{branch,tag}.{zip,tar.gz,tar.bz} to get a tag (release) release, which is different from the api itself (e.g. https://api.bitbucket.org/2.0/repositories/{user}/{repo}

Didn't find immediate results for being able to list available tags which is the only missing piece at this point preventing public bitbucket integration. Generally, bitbucket public API appears to be more limited. Private requires token usage like the thread above goes into and so will take longer to implement. 

Started experimentation with my own public repo, accessible via curl https://api.bitbucket.org/2.0/repositories/TheDuckCow/testopenproject/
At some level it appears http urls translate to their api urls, but is not immediately clear to me how to get more detailed information beyond the base responses.

```
https://api.bitbucket.org/2.0/repositories/TheDuckCow/testopenproject/downloads?tab=tags
# returns
{"pagelen": 10, "values": [], "page": 1, "size": 0}
```

I was also able to make and upload tags via, same as any git tagging from command line (bitbucket has no real interface for creating tags online)

```
git tag v0.0.1 -m "testing tags" # creates a non lightweight tag
git push origin v0.0.1
```

Also keeping in mind [this rate limit](https://confluence.atlassian.com/bitbucket/rate-limits-668173227.html), not dis-similar to [github](https://developer.github.com/v3/rate_limit/).

**Comment by TheDuckCow** [comment]
Revisiting this, I was able to find the way to list the explicit tag names for a repo:

`https://api.bitbucket.org/2.0/repositories/TheDuckCow/testopenproject/refs/tags`

This returns information such as this (truncated for key parts):

```
{
"pagelen":10,
"values":{
    {
        "type":"tag",
        "name":"v0.0.1",
        "links":{ ... },
        "target":{....},
    },
    { ... other tag ...}
},
"page":1,
"size":2
}
```
With this information and the above references found on being able to form the download link based on the tag name, we have everything that's needed. Even support for update to master would work (e.g. this link structure `https://bitbucket.org/TheDuckCow/testopenproject/get/master.zip`)

The next thing to tackle would be authentication - and how to safely store that authentication information (for any private repositories). This is also a milestone for github.

**Comment by carter2422** [comment]
Nice going @TheDuckCow! I've gone ahead and added an issue for Private Repositories; that is definitely a good goal and something that's bound to be requested a lot. https://github.com/CGCookie/blender-addon-updater/issues/13

**Comment by TheDuckCow** [comment]
Note that this enhancement has been completed and pushed to dev in the meantime, thanks to the initial work done by @blanchg we have a convenient structure that allows to integrate with any number of engines and initially did the support for bitbucket itself. 

I have since taken that structure and expanded it to support also GitLab (another hosting site with a git api). It's use is defined _within_ the updater module by:
```
self._engine = GitlabEngine()
```

Or, if you are outside the python module (where you don't have direct access to the engine classes), you can set the engine by:
```
from .addon_updater import Updater as updater
updater.engine = "Github"
# updater.engine = "GitLab"
# updater.engine = "Bitbucket"
```

Issue will be closed once the code is merged in from the according forks on those other platforms for testing.
