### ISSUE TITLE
in 2.80 doesnt working

### ISSUE THREAD

**Issue by koloved** [CGCookie/blender-addon-updater#47]
=(

**Comment by carter2422** [comment]
We are working on a 2.8 compatible version. Stay tuned!

**Comment by TheDuckCow** [comment]
Support has now been added to the master branch, sometime in near future will push the release for v1.0.6 as a tag, but you can at least start using the master branch in the meantime. Note that Blender 2.8 is still a beta and has been known to make breaking changes at any moment, best effort will be used to maintain this repository given this.

**Comment by telnetr4** [comment]
When we tried implementing the updater with our 2.80 addon we kept getting the following errors:
```rna_uiItemO: operator missing srna 'mb-lab.updater_check_now'
/home/USER/.config/blender/2.80/scripts/addons/MB-Lab/addon_updater_ops.py:936
rna_uiItemO: operator missing srna 'mb-lab.updater_update_target'
/home/USER/.config/blender/2.80/scripts/addons/MB-Lab/addon_updater_ops.py:1000
rna_uiItemO: operator missing srna 'mb-lab.updater_restore_backup'
/home/USER/.config/blender/2.80/scripts/addons/MB-Lab/addon_updater_ops.py:1012
```

Error is apparently due to the naming conventions in 2.80. It seems to be solved by changing the bl_idname from `bl_idname = updater.addon+".updater_install_popup"` to `bl_idname = "object.updater_install_popup"` but we are unsure if this would introduce new problems.

**Comment by TheDuckCow** [comment]
Hello,

Thanks for raising this issue. I would strongly advocate making your updater.addon be called “mb_lab” over “mb-lab”, as I suspect that is the issue being stricter in how dashes can be used. While yes you could rename the operators to be “object.updater_install_popup” etc, as soon as one other addon also using the updater module uses the same generic name, they will start to conflict and cause issues for both addons. 

Let me know if using underscores doesn’t fix the issue. 

Patrick W. Crawford

**Comment by schroef** [comment]
I think ive seen this issue with regular dashes in other addons as well. I believe its raising issues in some cases. I was checking the [Advanced UI Menus](https://github.com/Exairnous/Advanced-UI-Menus) and the bl 2.80 version also caused errors with the naming of dashes.

**Comment by telnetr4** [comment]
> I would strongly advocate making your updater.addon be called “mb_lab” over “mb-lab”, as I suspect that is the issue being stricter in how dashes can be used.

I set `updater.addon = "mb_lab"` and that works fine. You may want to add a troubleshooting note somewhere about this. Then again, anyone doing a search for this problem will hopefully end up here.
