### ISSUE TITLE
Error in Blender 2.80 release

### ISSUE THREAD

**Issue by Darkblader24** [CGCookie/blender-addon-updater#56]
Here is the error: https://i.imgur.com/F7kfXYy.png

**Comment by carter2422** [comment]
@Darkblader24 RetopoFlow doesn't yet work for Blender 2.8. We are actively working on the 2.8 version and will send out an email to all customers soon as it's ready.

**Comment by TheDuckCow** [comment]
This was resolved long ago, closing the ticket now - thanks for reporting initially!
