### ISSUE TITLE
Make annotations seems to skip missing text in operator

### ISSUE THREAD

**Issue by schroef** [CGCookie/blender-addon-updater#58]
I noticed the make annotation seems to be skipping over operator or props not having text="" properly added.

**Comment by TheDuckCow** [comment]
Can you share a code snippet or share where this happens? Are you seeing console warning outputs in this case, or is it causing other issues? When you say text="", it sounds more like you are referring to draw code issues, which is unrelated to the make annotations function. The warnings or errors that blender print out for not including `text=""` inside labels or operators inside draw functions is a forceful message from blender saying those fields are no longer "positional arguments", and must be named explicitly (where as they used to be positional).

Let me know if I misunderstand the context.

**Comment by TheDuckCow** [comment]
Closing this issue now, as the make_annotations is meant to address blender properties, and not change how UI draws/labels apply.
