### ISSUE TITLE
404 error when trying to reach gitlab update

### ISSUE THREAD

**Issue by Pullusb** [CGCookie/blender-addon-updater#64]
Hi !

Don't know if its an error on my side or a gitlab api change but I get an http error when trying to access release or master.

Console log :

```
Checking for update function
pipe_sync Updater: Read in JSON settings from file
Getting tags from server
HTTP error 404
master branch found, no releases {'name': 'Master', 'zipball_url': 'https://gitlab.com/api/v4/projects/pipe_sync/repository/archive.zip?sha=master'}
pipe_sync: Wrote out updater JSON settings to file, with the contents:
{'last_check': '2020-07-10 10:31:45.006835', 'backup_date': '', 'update_ready': False, 'ignore': False, 'just_restored': False, 'just_updated': False, 'version_text': {}}
pipe_sync BG thread: Finished checking for update, doing callback
```

here is my repo : https://gitlab.com/pullusb/pipe_sync

I specified this settings in *updater_ops*:

```
updater.engine = "GitLab"
updater.user = "pullusb"
updater.repo = "pipe_sync"
updater.website = "https://gitlab.com/pullusb/pipe_sync"
```

and up above :

```
# Must declare this before classes are loaded
# otherwise the bl_idname's will not match and have errors.
# Must be all lowercase and no spaces
updater.addon = "pipe_sync"
```

Can you tell me if I missed a step in the setup ?
I used the updater on another addon on github that works without issues...

**Comment by TheDuckCow** [comment]
Sorry I missed this report! There was actually a change on the side of GitLab. Took a little to understand, but the solve ended up being to assign a user agent int he request to GItLab, otherwise it would oddly give the 404s (as opposed to a 403 or something more logical in my mind). Check out this for what you need to change (noting it would be easiest to just refresh your whole addon_updater file, and maybe your ops file too while your add it to get a couple other tweaks/updates if):

https://github.com/CGCookie/blender-addon-updater/commit/7df2ecd22b4dca9a95052de1ff82c201990c14d5#diff-33519f494e14056cda95e8be5623321aR644

Let me know if that solves it for you!

**Comment by Pullusb** [comment]
Hi,
The thing is, I was already in 1,0,8 (last) version of your script (should have mentionned this), but always get http 404 error, I re-checked with a diff comparison.
Maybe gitlab API re-changed since last modification.

**Comment by TheDuckCow** [comment]
Interesting, not immediately sure here. I just checked with two other GitLab addons (one public and one private using tokens), but are still pulling updates fine (tested both check for update as well as installing a target version).

I just tried running the very raw level python inside of a script editor in blender 2.83 (to prove it runs fine with the version of python packaged with blender); can you see if this code also runs fine for you, and prints out tags to the console as I see? I already copied in your project ID so you can run as-is.

```
import ssl
import urllib.request

print(ssl.OPENSSL_VERSION)
api_url = 'https://gitlab.com'
repo = "19861010"

url = "{}{}".format(api_url,"/api/v4/projects/",repo,"/repository/tags")

request = urllib.request.Request(url)
context = ssl._create_unverified_context()
result = urllib.request.urlopen(request,context=context) # issue occurs here within blender
result_string = result.read()
result.close()
get = result_string.decode()
print(get)
```

**Comment by Pullusb** [comment]
Ok this seem run fine for me too. No error (but I dont really get where you get the tags in this) 
Here is the console output (just added some returns)
[console_output.txt](https://github.com/CGCookie/blender-addon-updater/files/5068540/console_output.txt)

I must be missing an obvious error somewhere. Will tinker a bit more later.
Thanks for your help

**Comment by TheDuckCow** [comment]
Any luck on this?

**Comment by Pullusb** [comment]
Just tried again this morning, Since it worked with the repo id instead of the repo name with your snippet, I just changed this and it works fine now.

Trying to reach tags or master branch with repo name gave an error even in browser :

![firefox_391bEywP0Z](https://user-images.githubusercontent.com/7763187/90495441-ed17b100-e144-11ea-973b-0d38400fbbf2.png)

![firefox_ZbFcidkNAZ](https://user-images.githubusercontent.com/7763187/90495455-f012a180-e144-11ea-8724-559adae8bab2.png)

So I'm now in this configuration:

![Code_xx79WswV3J](https://user-images.githubusercontent.com/7763187/90495574-0d477000-e145-11ea-8299-e35167c59b92.png)

```
updater.engine = "GitLab"
updater.user = ""
updater.repo = "19861010"
updater.website = "https://gitlab.com/pullusb/pipe_sync"
```

You can close the issue

**Comment by TheDuckCow** [comment]
Yes indeed, for GitLab you *have* to use the id. The term "repo" makes more sense as you use the actual repo name for the GitHub and Bitbucket variants. GitLab just defines their API differently and thus requires. it to be setup this way. Let me know if you think there's a way we could make this point of using the ID more obvious. Right now, it's a subbullet [under here](https://github.com/CGCookie/blender-addon-updater#addon_updater-module-settings) and under step four [here](https://theduckcow.com/2016/addon-updater-tutorial/).

I suppose the answer would be, update the comment in the code itself to call out GitLab being special?

**Comment by Pullusb** [comment]
Yes, after `must match git name`, add something like `, for gitlab use project ID`
