### ISSUE TITLE
reload_addon in 2.8x

### ISSUE THREAD

**Issue by Dragorn421** [CGCookie/blender-addon-updater#66]
# The issue

reload_addon() is failing in Blender 2.82:

```Error: Traceback (most recent call last):
  File "...\Blender\2.82\scripts\addons\...\addon_updater_ops.py", line 377, in execute
    clean=self.clean_install)
  File "...\Blender\2.82\scripts\addons\...\addon_updater.py", line 1349, in run_update
    res = self.unpack_staged_zip(clean)
  File "...\Blender\2.82\scripts\addons\...\addon_updater.py", line 933, in unpack_staged_zip
    self.reload_addon()
  File "...\Blender\2.82\scripts\addons\...\addon_updater.py", line 1054, in reload_addon
    bpy.ops.wm.addon_disable(module=self._addon_package)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\bpy\ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
AttributeError: Calling operator "bpy.ops.wm.addon_disable" error, could not be found
```

# The reason

[reload_addon in addon_updater.py](https://github.com/CGCookie/blender-addon-updater/blob/master/addon_updater.py#L1041)

```py
		bpy.ops.wm.addon_disable(module=self._addon_package)
		bpy.ops.wm.addon_refresh()
		bpy.ops.wm.addon_enable(module=self._addon_package)
```

Apparently at some point those operators moved from `bpy.ops.wm.` to `bpy.ops.preferences.`

# A fix

Replacing the previous code excerpt with this allowed the module to reload in Blender 2.82:

```py
		try:
			# < 2.80
			bpy.ops.wm.addon_disable(module=self._addon_package)
			bpy.ops.wm.addon_refresh()
			bpy.ops.wm.addon_enable(module=self._addon_package)
		except AttributeError: # 2.80+
			bpy.ops.preferences.addon_disable(module=self._addon_package)
			bpy.ops.preferences.addon_refresh()
			bpy.ops.preferences.addon_enable(module=self._addon_package)
```

Not sure `except AttributeError` is the best check. `hasattr` doesn't seem to be a possibility under `bpy.ops` for reasons I don't know/understand

**Comment by TheDuckCow** [comment]
Thanks for flagging, definitely missed this as I don't run addons with this auto reload code often (I find it's ultimately just not as reliable as having the user restart blender).

Regarding your point on hasattr, are you referring to the fact that `hasattr(bpy.ops.wm, "addon_disable")` returns true even in blender 2.8? I think it's a consequence for some api remnants existing. However, the following check does correctly return False for blender 2.8, and is probably what I'll implement: `"addon_disable" in dir(bpy.ops.wm)`. Could also do the reverse, hasattr for preferences and the addon_disable under there.

Will work on this change, unless you want to beat me to a pull request!

**Comment by Dragorn421** [comment]
`"addon_disable" in dir(bpy.ops.wm)` indeed returns `True` in 2.79b and `False` in 2.82 (those being the two Blender versions I use)

I'll let you do the changes if you don't mind :)

**Comment by TheDuckCow** [comment]
Sure thing, I'll reply back here when done - likely next week!

**Comment by TheDuckCow** [comment]
Haven't packaged into a release, but the master code has now been updated for you if you want to pull from that. I did see it worked with 2.8, and my locally run test added in that last commit indeed also passed.

**Comment by Dragorn421** [comment]
Tests also passed in 2.79b

I don't get to use the updater a lot but people have been reporting crashes due to the reloading so I'll actually stop using it, as recommended. Thanks for the fix though! You can mark this closed if you consider the issue fixed (I do)

**Comment by Dragorn421** [comment]
Actually I do have an issue about the reload test in 2.82 but it's more likely a test script issue? I'll let you figure it out

<details>
<summary>Click to show output</summary>

```
blender-addon-updater/tests$ /mnt/c/Program\ Files/Blender\ Foundation/Blender\ 2.82/blender.exe -b -P addon_updater_test.py
Blender 2.82 (sub 7) (hash 77d23b0bd76f built 2020-02-13 01:56:46)
Read prefs: D:\redacted\AppData\Roaming\Blender Foundation\Blender\2.82\config\userpref.blend
found bundled python: C:\Program Files\Blender Foundation\Blender 2.82\2.82\python
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'io_export_objex2_2_82'
Running Updater Tests
...addon_utils.disable: blender-addon-updater-github not disabled
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'blender-addon-updater-github'

Error: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'blender-addon-updater-github'

Error: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'blender-addon-updater-github'

E.
======================================================================
ERROR: test_reload_callbacl (__main__.TestFunctions)
Test the reload function which disables and re-enables addon
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\redacted\blender-addon-updater\tests\addon_updater_test.py", line 218, in test_r
eload_callbacl
    updater.reload_addon() # assert no error
  File "D:\redacted\blender-addon-updater\addon_updater.py", line 1088, in reload_addon
    bpy.ops.preferences.addon_enable(module=self._addon_package)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\bpy\ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'blender-addon-updater-github'



----------------------------------------------------------------------
Ran 5 tests in 75.461s

FAILED (errors=1)
```

</details>

**Comment by TheDuckCow** [comment]
Hi there, yeah that's likely due to an assumption of the name of the folder zipped up and installed in blender. The module name = the addon folders name, and because I test versions for also gitlab and bitbucket, I explicitly rename it to be -github under blender addons. If you renamed the addon's installed folder to be `blender-addon-updater-github` I would expect the tests to run fine.

Just to affirm, when I run the below, all tests pass (and that's with the latest code):
```"/Applications/Blender 2.83/Blender.app/Contents/MacOS/Blender" -b -P addon_updater_test.py```

Thanks again for giving the test file a go, appreciate that! Closing in meantime, let me know if any other troubles come up.
