### ISSUE TITLE
Failures to delete directories

### ISSUE THREAD

**Issue by Dragorn421** [CGCookie/blender-addon-updater#67]
# Context

Some users and myself have been having issues, all linked to filesystem operations, on Windows, with different Blender 2.7x/2.8x versions.

[Relevant Addon using blender-addon-updater](https://github.com/CrookedPoe/io_export_objex/tree/master/io_export_objex2) / [Latest revision at time of writing](https://github.com/CrookedPoe/io_export_objex/tree/ba207542152f949f49ef8b88fa5aaa8a4486bf5e)

This isn't a permissions issue as the addon can create the `*_updater` folder

# Issue 1

A user encountered this when trying to update

<details>
<summary>Click to expand</summary>

![error in ui](https://cdn.discordapp.com/attachments/631723103830933504/743962636017860608/Capture.PNG)

![delete folder errors in console](https://cdn.discordapp.com/attachments/631723103830933504/743963073358069861/Capture.PNG)

</details>

Deleting the folder manually allowed the updater to function properly then.

# Issue 2

I also had weird issues originating from shutil (I don't have the logs anymore sorry) which may have been due to paths being too long

The real issue being that those paths became too long because the addon was backuping its backups, after failing to delete previous backups. shutil failed midway through traversing the directory tree.

# Fix

?

I think it would be better to not catch-all and ignore exceptions like [here](https://github.com/CGCookie/blender-addon-updater/blob/master/addon_updater.py#L711), because it clearly prevents us here to actually understand what's going on.

**Comment by TheDuckCow** [comment]
Firstly, *thank* you sharing your steps, screenshots, and troubleshooting so far.

Regarding the fix, I think it's fair that we should at least print the raw, full traceback message to the console. I'd still like to pass forward the more user friend message, which is what the error handler there does. We could also capture the error in the message presented to the UI too, so anyone who screenshots it gets that.

As for the other points about recursive backups, that sounds plausible. Especially if there were prior errors. The updater should do a better job at skipping that backup/tmp folder when running a backup, regardless of the circumstances.

No immediate ETA, but this is what I would work on.

**Comment by TheDuckCow** [comment]
FYI that I created this commit which should largely address the original issue (so long as the issue has more to do with excessive long paths in the backup folder): https://github.com/CGCookie/blender-addon-updater/commit/44bc9439d422c2c03c3776d90ad45bae1903d379

Closing in the meantime, but if you do happen to try this and find issues, let me know.
