### ISSUE TITLE
Cancel background check for update

### ISSUE THREAD

**Issue by TheDuckCow** [CGCookie/blender-addon-updater#7]
A previous proposal from @carter2422 from before was to see if we could add a "cancel button" for while the background thread is running/checking for an update. This way, if the request tis taking too long the user can cancel it.

**Comment by TheDuckCow** [comment]
I have spent some time thinking about and looking into this issue, which is interesting for the following reason: The background check for update process is already represented in a daemon thread. _There is no graceful way to force close or halt another thread_ and there are several posts that talk about the various non-graceful ways. I'm extending the original request to relate to 1) cancelling a check for update and 2) cancelling the pulling down the code of the update.

[This is a related read](http://stackoverflow.com/a/11822850/3624678) although not exactly the same scenario, as we are essentially grabbing a single (json or zip) file via the github api request and that article is about downloading multiple large files. Essentially, I see the following solutions to this problem/request:

**Check for update**
- Don't actually change anything. If the request is taking too long, let it stay in that status as it doesn't block the use of blender in any way since everything is in a daemon background thread
- Build in polling into the interrupt urllib download function call; that is, find a way to used a shared "cancel thread" variable that when set would interrupt the download. This honestly doesn't make much sense to do as we are retrieving a single file already so the interrupt shared variable would still get blocked/queued while the request happens. It's also a lot of unnecessary work since ultimately this is hardly going to be more information grabbing than a ping. 
- **[my recommendation]** Don't actually change anything module-wise, but still provide a "cancel button" which would reset the UI so you can try checking again. The daemon thread will still exist and be trying to pull the git-generated json file in the background, but the user interface won't look like it's stuck. The daemon thread will eventually exit successfully or fail naturally and not affect anything. I argue this is completely fine because it's such a lightweight request, and if it's being that slow, then everything to the user is being slow internet wise and as long as it's not blocking blender use, shouldn't be a problem. 

**Downloading the update**
Here, I need more input on how we want it to behave. Currently, downloading the code is not in a background thread as I was thinking we didn't want the user to interact/use blender while modules are being swapped around - and this also prevents us from providing a blocking UI popup or any other form of a cancel button unless we thread the download process. Some thoughts:
-  Given that we now are asking the user to restart blender to get the update anyways, I don't think it makes sense to block them from using blender - especially for any larger addons. 
-  But if we do still move the downloading to a daemon thread like `check for update` already is, then the user can press e.g. "okay to download update in background" and continue using blender
- But, background means background - they aren't forced to wait for the operation to complete. And if we wanted a cancel button, it would have to be either in preferences or in the addon's panel (but couldn't be in a popup since we can't control when poopups close, nor can we re-draw a popup unless we close & re-trigger)
- Then, cancel button aside, how do we notify the user when it's done and they can restart blender?
  - We could do a popup when download is done (this is already implemented and used), but would potentially interrupt the user if they started using blender normally after setting check for update in background
  -  We could update the panel to say "download complete, restart when ready". 
  -  We could just pre-instruct them to restart blender at their convenience after the download has completed (assumes we update panel/preferences to indicate when download finished) and not to restart blender before then. Risk is if they restart before the download completed, will need to do it again (in this case, it would just trigger an update-ready popup again, as if they didn't click it before)
- At the moment, I'm not decided which way is best (to block blender while it downloads or to put it to background, and how to notify use if we do go background), and thus may even be something we leave up to the developer to decide through different configuration settings of the module. But we need to make a decision for at least the example module as-is, and for the pilot implementation in retopoflow
- **My recommendation:** Either:
  -  Leave it as-is (ie not background-threaded and block blender until it's done downloading updated code, and no cancel button), or:
  -  Make it background threaded (new piece) & have a popup (easily implemented) to tell them to restart when it is done downloading, knowing that in most cases the popup should happen relatively quickly. In this case, we could still have a "cancel" button, but for the same reasons as above in the check for update discussion, we can't actually cancel the background thread spontaneously. 
    -  Caveat to that last point on no cancel button: Unlike the check for update, which grabs a very small file (json request essentially), here a cancel operation could be plausible/sensible. We could copy & modify a lower-level downloading module so we can break the download into chunks where we could insert snippets of code to send updates to the main blender/ui thread between chunks or check for a request to cancel download via a shared variable flag (user presses cancel download, flag is set, next time the background thread gets to the flag check, it halts the progress). Downloading by chunks would take a bit more time to implement and thus may be good for a post v1 release improvement.

What are you thinking would be best, @carter2422 or anyone else?

**Comment by TheDuckCow** [comment]
Implemented the cancel background thread feature, though really is just a UI change since we cant' safely cancel the background process for checking (something can be implemented for background updating).

Currently, if there is no internet connectivity, this allows you to cancel the checking which gets stuck. I'm working to improve the backend thread to respond back to indicate it could not connect to the API (ie check connectivity).

**Comment by carter2422** [comment]
Thanks @TheDuckCow; with the background thread implemented are you still needing input on the direction here or are we good to go?

From my perspective, so long as the user cannot inadvertently corrupt the install (within reason), and are clearly presented with what's happening them I'm happy for now.

**Comment by TheDuckCow** [comment]
To quote you, "Let's keep it simple 👍" so I'm all good 😄  leaving it as it is for now.
