### ISSUE TITLE
Can't find __init__ file

### ISSUE THREAD

**Issue by StandingPadAnimations** [CGCookie/blender-addon-updater#72]
So I tried testing the addon updater but when I click update, it has this error
![image](https://media.discordapp.net/attachments/737872746700079235/820789379806527488/unknown.png)

**Comment by StandingPadAnimations** [comment]
Never mind, it turns out that I didn't have a init file in the main repository and it was only in the release

**Comment by TheDuckCow** [comment]
Interesting, so this was due to some local modifications you had (ie a normal user wouldn't run into this)?

*edit*: just now realized what repository this was! So never mind, but thanks for proactively trying to report!
