### ISSUE TITLE
Add Cancel button to new update modal

### ISSUE THREAD

**Issue by carter2422** [CGCookie/blender-addon-updater#8]
The modal for new versions is great (https://cl.ly/hQRD) but let's add a "Not now" button to dismiss the modal. You can click out of it already but this is not clear to the user, so it almost feels like an update trap.

**Comment by TheDuckCow** [comment]
Following our call from today, it currently is using an operator so we cannot change the OK button or make a dismiss button (or at least, it wouldn't actually close the window); solution is to add text telling the user to press esc to choose to not update now.

**Comment by TheDuckCow** [comment]
Made the above change, will be present in next push.
