### ISSUE TITLE
Updater does not show option to choose version/branch

### ISSUE THREAD

**Issue by agajdosi** [CGCookie/blender-addon-updater#82]
So, for some reason the updater does not show me option to choose version or branch. It does sometimes but most of the time it just installs the last version without ability to choose.

**Comment by TheDuckCow** [comment]
Hey @agajdosi apologies for the delayed reply, can you share your repo where you have this configured? Will be easiest to look at specific; you could also just pasted in the section of your `def register` function in the ops file, as that has most of the config.

**Comment by agajdosi** [comment]
Hi @TheDuckCow, thank you for the reply. Here is the file: https://github.com/BlenderKit/blenderkit/blob/master/addon_updater_ops.py I have tried to track it down, but I could not really find the problematic change. Thanks for taking a look!

**Comment by TheDuckCow** [comment]
Hi @agajdosi I believe this would be the issue, set [this line](https://github.com/BlenderKit/blenderkit/blob/master/addon_updater_ops.py#L1456) to `True` and [this line](https://github.com/BlenderKit/blenderkit/blob/master/addon_updater_ops.py#L1473) needs to list the branches if you want to show anything other than tags.

However I tried your latest build, there is something else funny about your operator `bpy.ops.mcprep.updater_update_target()` as it isn't invoking the popup to select between versions (ie this button should create a popup to select different versions, but for me it's just immediately jumping to install... I don't know what version).

<img width="489" alt="Screen Shot 2022-10-30 at 11 41 07 AM" src="https://user-images.githubusercontent.com/2958461/198893038-466e6ee8-e0c7-4e14-9139-3f355c278228.png">

Are you aware of any custom modification of the module? Looks like the draw code is specifically forcing users to install:

```
bpy.ops.blenderkit.updater_update_target(target='BlenderKit 3.3.0.221027', clean_install=False)
```

You should get a popup like this (reference: the [MCprep addon](https://github.com/TheDuckCow/MCprep/blob/master/MCprep_addon/addon_updater_ops.py)); while this repo doesn't have the option to include branches, this is where they would show up if enabled:
<img width="340" alt="Screen Shot 2022-10-30 at 11 44 03 AM" src="https://user-images.githubusercontent.com/2958461/198893151-c38bcb2c-a822-45fc-8a33-d1a71b7ce9b0.png">

**Comment by TheDuckCow** [comment]
Closing this issue as it has bene awhile, but let me know if still an open issue.

**Comment by agajdosi** [comment]
@TheDuckCow Sorry for the delay, missed the emails. The issue dissapeared, seems good right now, will let you know if it fails again.
