### ISSUE TITLE
Option to enable pre-releases in the preferences

### ISSUE THREAD

**Issue by agajdosi** [CGCookie/blender-addon-updater#87]
It would be great if the updater had an option to enable prereleases for users who want to try the latest version of the add-on and are willing to test and risk a little bit. It would help the add-on developers to follow the RERO philosophy: Release early, release often.

I have implemented this for BlenderKit add-on where we wanted to improve the quality of the add-on and make it as easy as possible for the users to update to alpha, beta releases. TBH it works quite nice and I am happy with that - from 160k downloads on normal release we have 1k downloads on alphas. This base of users who helps us by using the prereleases is great.

How it could work is:
- currently in the updater you can define strings which if contained in the branch/release/tag means this release is ignored
- the prereleases update give option to users to easily ignore this check, so they can update do prereleases

I would like to create a PR from the edits as I believe it could be useful for other add-on creators and users. Please let me know if this is something which seems good to you.

![Screenshot 2023-04-13 at 16 55 02](https://user-images.githubusercontent.com/22000268/231799748-b7938019-7600-4cf3-af64-619ecbf13fba.png)

**Comment by schroef** [comment]
That should be doable, i remember i added the option to add releases. If that is enabled in the addon you can actually pick a release yourself. I think it can actually do what you want. See this link; https://github.com/CGCookie/blender-addon-updater/issues/24#issuecomment-377286872

It looks like this in the addon
![Screen Shot 2023-04-13 at 11 15 26](https://user-images.githubusercontent.com/6923008/231805992-d3d55a76-dec2-45b3-90bb-fd4a75c2be1f.png)

You need to enable this in the addon part if you want to add it

**Comment by schroef** [comment]
This is the actuall pull from 2018 where i added the functionality

https://github.com/CGCookie/blender-addon-updater/pull/38

**Comment by TheDuckCow** [comment]
I'm going to close this as the suggestions by @schroef are on the right track, and any such implementation will be quite specific to naming conventions/flows that a given addon developer would want. If there's still questions, just chime back in on this thread!
