### ISSUE TITLE
Ignore update popup persistence

### ISSUE THREAD

**Issue by TheDuckCow** [CGCookie/blender-addon-updater#9]
From previous feedback, if a user presses the "dismiss" button for an update, it should remove the entire panel on the view so they must move to the preferences to check or run updates. 

Also, if the user presses ignore, verify whether it persists after future updates complete or if the ignore popup remains silent. My thought is that pressing ignore would set a property in the preference for silent background checks if auto-check is enabled. This value is then loaded/set based on the persistent json saved date so that whenever it is toggled, the state is saved regardless if the user presses save preferences or not.

**Comment by TheDuckCow** [comment]
Implemented. If update is ready initially, will show a popup/panel (assuming developer configured the addon to show these, as is the default setup). If the user presses ignore, then the panel will disappear and the info window will indicate it can be seen manually from the preferences panel if needed. Then, popups won't show up until after the next time the user attempts to install an update; just checking will not clear the ignore stance, only after pressing update (even if it fails)

**Comment by carter2422** [comment]
Nice @TheDuckCow! 

I'm hoping to get that initial announcement post and the RetopoFlow version done in the next few weeks, after the new Blender Market site launches this week.

**Comment by TheDuckCow** [comment]
Cool, I should be done and polished in the next couple days and then spend the remaining time beefing out the documentation. Good luck with the new launch!

**Comment by carter2422** [comment]
Sounds great! And thanks :)
